# Generated by Django 4.2.6 on 2023-10-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptogasto',
            name='estado',
            field=models.CharField(max_length=255),
        ),
    ]
